### PR TITLE
Implement geocoding

### PR DESCRIPTION
**Pull request by AlissaWe**
Implement geocoding and reverse geocoding search functions.
`geocoding_id()` only partially implemented because database does not yet contain required data.

Fixed issue #5 using Photon.

### CODE REVIEW

**Review by rleh — APPROVED** [review]
Great 👍 😉

**Comment by rleh** [comment]
Merge @Harry-R ?

**Comment by Harry-R** [comment]
Thanks for your contribution 👍

**Comment by rleh** [comment]
Seems like [this function](https://github.com/OpenCycleCompass/ocyco-server-python/blob/2ab638f13ee3d104bcb7de9d1971050a7fa04697/app/utils.py#L9) should needs geocoding too

**Pull request merged**
